imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: fr

framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        mappings:
            notification:
                type:      yml
                alias:     Event
                is_bundle: false
                prefix:    EPE\Component\EventEntity\Entity
                dir:       "%kernel.root_dir%/../vendor/epe/component-event-doctrine/src/Resources/config/event"


fos_rest:
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json : true
        templating_formats:
            html: true
        force_redirects:
            json: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: php
    routing_loader:
        default_format: json
        include_format: false

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            Notification:
                namespace_prefix: "EPE\\Component\\EventEntity\\Entity"
                path: "%kernel.root_dir%/config/serializer/event/"

nelmio_cors:
    paths:
        '^/':
            allow_credentials: false
            allow_origin: ['*']
            allow_methods: ['POST', 'OPTIONS', 'PUT', 'GET', 'PATCH', 'HEAD', 'DELETE']
            allow_headers: ['origin', 'x-requested-with', 'content-type', 'authorization']

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable: true
