app_calendar:
    resource: "@AppBundle/Controller/CalendarController.php"
    type:     rest
    prefix:   /v1

app_event:
    resource: "@AppBundle/Controller/EventController.php"
    type:     rest
    prefix:   /v1

app_unavailability:
    resource: "@AppBundle/Controller/UnavailabilityController.php"
    type:     rest
    prefix:   /v1

app_address:
    resource: "@AppBundle/Controller/AddressController.php"
    type:     rest
    prefix:   /v1

app_timesheet:
    resource: "@AppBundle/Controller/TimesheetController.php"
    type:     rest
    prefix:   /v1

app_profile:
    resource: "@AppBundle/Controller/ProfileController.php"
    type:     rest
    prefix:   /v1

