imports:
    - { resource: services/definition.yml }
    - { resource: services/manager.yml }
    - { resource: services/form.yml }

parameters:
    app.address.entity:        EPE\Component\EventEntity\Entity\Address
    app.calendar.entity:       EPE\Component\EventEntity\Entity\Calendar
    app.event.entity:          EPE\Component\EventEntity\Entity\Event
    app.timesheet.entity:      EPE\Component\EventEntity\Entity\Timesheet
    app.profile.entity:        EPE\Component\EventEntity\Entity\Profile
    app.unavailability.entity: EPE\Component\EventEntity\Entity\Unavailability

services:
    app.yaml_parser:
        class: Symfony\Component\Yaml\Yaml

    app.form_handler:
        class: AppBundle\Form\Handler

    app.definition:
        class: AppBundle\Definition\Definition
        arguments:
            - "@app.yaml_parser"
            - "%kernel.root_dir%/config/services/definition.yml"

    app.resource_adapter:
        class: Ugosansh\Component\EntityManager\Adapter\DoctrineResourceAdapter
        arguments:
            - "@doctrine.orm.entity_manager"