EPE\Component\EventEntity\Entity\Profile:
    properties:
        id:
            read_only: true
        parameters:
            expose: false
            exclude: true
        unavailabilities:
            expose: false
            exclude: true

    relations:
        - rel: self
          href:
            route: get_profile
            parameters:
                id: expr(object.getId())
