services:
    app.calendar.form_type:
        class: AppBundle\Form\Type\CalendarType
        calls:
            - [ setDataClass, ['%app.calendar.entity%'] ]
            - [ setProfileManager, ['@app.profile.manager'] ]
        tags:
            - { name: form.type }

    app.event.form_type:
        class: AppBundle\Form\Type\EventType
        calls:
            - [ setDataClass, ['%app.event.entity%'] ]
            - [ setEventManager, ['@app.event.manager'] ]
            - [ setCalendarManager, ['@app.calendar.manager'] ]
        tags:
            - { name: form.type }

    app.unavailability.form_type:
        class: AppBundle\Form\Type\UnavailabilityType
        calls:
            - [ setDataClass, ['%app.unavailability.entity%'] ]
            - [ setCalendarManager, ['@app.calendar.manager'] ]
        tags:
            - { name: form.type }

    app.address.form_type:
        class: AppBundle\Form\Type\AddressType
        calls:
            - [ setDataClass, ['%app.address.entity%'] ]
        tags:
            - { name: form.type }

    app.profile.form_type:
        class: AppBundle\Form\Type\ProfileType
        calls:
            - [ setDataClass, ['%app.profile.entity%'] ]
        tags:
            - { name: form.type }

    app.timesheet.form_type:
        class: AppBundle\Form\Type\TimesheetType
        calls:
            - [ setDataClass, ['%app.timesheet.entity%'] ]
        tags:
            - { name: form.type }
