services:
    app.address.manager:
        class: AppBundle\Manager\AddressManager
        arguments:
            - "@app.resource_adapter"
            - "%app.address.entity%"

    app.calendar.manager:
        class: AppBundle\Manager\CalendarManager
        arguments:
            - "@app.resource_adapter"
            - "%app.calendar.entity%"

    app.event.manager:
        class: AppBundle\Manager\EventManager
        arguments:
            - "@app.resource_adapter"
            - "%app.event.entity%"

    app.timesheet.manager:
        class: AppBundle\Manager\TimesheetManager
        arguments:
            - "@app.resource_adapter"
            - "%app.timesheet.entity%"

    app.profile.manager:
        class: AppBundle\Manager\ProfileManager
        arguments:
            - "@app.resource_adapter"
            - "%app.profile.entity%"

    app.unavailability.manager:
        class: AppBundle\Manager\UnavailabilityManager
        arguments:
            - "@app.resource_adapter"
            - "%app.unavailability.entity%"
