EPE\Component\EventEntity\Entity\Calendar:
    properties:
        name:
            - NotBlank:
                message: validator.constraints.not_blank
            - Length:
                minMessage: validator.constraints.length_min_3
                maxMessage: validator.constraints.length_min_64
                min: 3
                max: 64