EPE\Component\NotificationEntity\Entity\NotificationType:
    properties:
        title:
            - NotBlank:
                message: validator.constraints.not_blank
            - Length:
                minMessage: validator.constraints.length_min_3
                maxMessage: validator.constraints.length_min_32
                min: 3
                max: 64
        title:
            - NotBlank:
                message: validator.constraints.not_blank
            - Length:
                minMessage: validator.constraints.length_min_3
                min: 3
        enabled:
            - Type:
                type: bool
        formats:
            - Type:
                type: array
            - NotBlank:
                message: validator.constraints.not_blank
            - NotNull:
                message: validator.constraints.not_null